create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null,
    email text not null unique,
    password_hash text not null,
    created_at timestamptz not null
);

create table if not exists public.quotes (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    quote text not null,
    author text,
    source text,
    reason text,
    emotion text,
    favorite integer default 0,
    is_public integer default 1,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table if not exists public.reflections (
    id bigint generated by default as identity primary key,
    quote_id bigint not null,
    user_id bigint not null references public.users(id),
    memo text not null,
    emotion text,
    created_at timestamptz not null,
    is_shared integer default 0
);

create table if not exists public.friends (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    friend_id bigint not null references public.users(id),
    status text not null,
    created_at timestamptz not null,
    unique (user_id, friend_id)
);

create table if not exists public.shared_stars (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    original_quote_id bigint not null references public.quotes(id),
    original_user_id bigint not null references public.users(id),
    quote text not null,
    author text,
    source text,
    emotion text,
    reason text,
    created_at timestamptz not null,
    favorite integer default 0
);

create table if not exists public.favorite_rankings (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id),
    quote_id bigint not null,
    is_shared integer default 0,
    rank integer not null,
    updated_at timestamptz not null,
    unique (user_id, rank)
);

create table if not exists public.friend_star_comments (
    id bigint generated by default as identity primary key,
    star_owner_id bigint not null references public.users(id),
    quote_id bigint not null,
    is_shared integer default 0,
    commenter_id bigint not null references public.users(id),
    comment text not null,
    created_at timestamptz not null
);

alter table public.users enable row level security;
alter table public.quotes enable row level security;
alter table public.reflections enable row level security;
alter table public.friends enable row level security;
alter table public.shared_stars enable row level security;
alter table public.favorite_rankings enable row level security;
alter table public.friend_star_comments enable row level security;
